name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dotnetcore31:
    name: '3.1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: ./Build/CI/tests.sh
        env:
          BUILD_ARGS: /p:AdditionalDefineConstants=SECP256K1_VERIFY
          Framework: netcoreapp3.1
  dotnetcore31standard20:
    name: '3.1 with netstandard2.0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: ./Build/CI/tests.sh
        env:
          BUILD_ARGS: /p:TargetFrameworkOverride=netstandard2.0
          Framework: netcoreapp3.1